# Generated by Django 6.1.1 on 2026-09-29 09:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price_delta', models.DecimalField(decimal_places=0, default=0, help_text='Amount added to the base price, in tomans.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-datetime_created',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-datetime_created',)},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='Hours needed to prepare this product.'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='top_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_categories', to='store.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['product', 'status'], name='store_comme_product_9e48a2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'slug'], name='store_produ_categor_48504b_idx'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.product'),
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.productoption'),
        ),
        migrations.AddConstraint(
            model_name='productoption',
            constraint=models.UniqueConstraint(fields=('product', 'slug'), name='unique_option_slug_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productoptionvalue',
            constraint=models.UniqueConstraint(fields=('option', 'slug'), name='unique_value_slug_per_option'),
        ),
    ]
