# Generated by Django 6.1.1 on 2026-09-29 10:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_discount_alter_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='discount_offer',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_offer',
        ),
        migrations.AddField(
            model_name='discount',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='used_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_discount', to='store.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('first', 'First purchase'), ('referral', 'Referral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['customer', 'discount_type'], name='store_disco_custome_5b16f9_idx'),
        ),
    ]
