# Generated by Django 6.1.1 on 2026-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_payment_options_payment_authority_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'p')), fields=('order',), name='one_pending_payment_per_order'),
        ),
    ]
